### ISSUE TITLE
404 page not working

### ISSUE THREAD

**Issue by xeon-zolt** [Meilix-Generator/meilix-generator#6]
https://github.com/Meilix-Generator/meilix-generator/blob/master/app.py/#L15-L18

this is not working
```
@app.errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404
```
but this is working
```
@app.errorhandler(404)
def application_error(e):
    return 'Sorry, unexpected error: {}'.format(e), 404
```

**Comment by meets2tarun** [comment]
Would you please tell me the way to reproduce the error?

**Comment by xeon-zolt** [comment]
Have you ran the current code 
Is 404 page working ?
No its not
