### ISSUE TITLE
Logo for meilix-generator

### ISSUE THREAD

**Issue by meets2tarun** [Meilix-Generator/meilix-generator#8]
We need a logo for the meilix-generator

**Comment by xeon-zolt** [comment]
current one is ok i think

**Comment by xeon-zolt** [comment]
![18982333f8d0191fe1bf2f723c7719b4](https://cloud.githubusercontent.com/assets/4529442/26763336/fa3e4c2a-496e-11e7-8e9f-735154fac36a.jpg)
